name: Bug
description: Report a bug that occured when you used the official website of Lastand Development.
title: "Bug: "
labels: "bug"
assignees: "LastandDevelopment"
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 

        ---

        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: input
    id: browser
    attributes:
      label: Browser
      description: "Which browser did you use? Please provide the version as well."
      placeholder: "Google Chrome 100"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: "In which version of the website did the bug occur? You can find it in the About-Dialog."
      placeholder: "1.8.3"
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do I need to take to reproduce this bug?
    validations:
      required: true
