blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/LastandDevelopment/website/discussions
    about: If you want to tell me your opinion on the website, post it in the discussions tab.
