name: Feature Request
description: Post your idea for a new feature here.
title: "Feature Request: "
labels: "request"
assignees: "LastandDevelopment"
body:
  - type: markdown
    attributes:
      value: |
        Before posting your feature request, please make sure that feature does not exist in the latest version of the game. You can download the latest version on: https://sites.google.com/view/lastanddevelopment/meteor-extinction/all-versions
        
        ---
        
  - type: textarea
    id: featuredescription
    attributes:
      label: Feature description
      description: Describe your idea for a new feature.
    validations:
      required: true