name: Feature Request
description: Post your idea for a new feature here.
title: "Feature Request: "
labels: "request"
assignees: "LastandDevelopment"
body:
  - type: markdown
    attributes:
      value: |
        Before posting your feature request, please make sure that feature does not exist.
        
        ---
        
  - type: textarea
    id: featuredescription
    attributes:
      label: Feature description
      description: Describe your idea for a new feature.
    validations:
      required: true
